### ISSUE TITLE
Logging API keys

### ISSUE THREAD

**Issue by daniel-moulton** [Exeter-Computer-Science-Society/excs-website#2]
In the Map component, an API key is being logged to console. Current output is undefined (I'm assuming the API keys have not been set hence the MapTiler component not working on event pages).

Should definitely be removed as soon as possible.

https://github.com/Exeter-Computer-Science-Society/excs-website/blob/1d20f94a59fa4190db51d876f963aa993f06b2bd/components/Map/index.jsx#L22

**Comment by inspizzz** [comment]
Will remove this debugging line, also looking into ways of securely storing api keys and server components + env + contexts seem to be the best way

**Comment by inspizzz** [comment]
- Created new api key in maptlier
- added secure env file to the server

Fixed in commits:
[#858b4454444d6beff6cdd91c14ad1852db93bedf](https://github.com/Exeter-Computer-Science-Society/excs-website/commit/858b4454444d6beff6cdd91c14ad1852db93bedf)
[#d6df8f1ffa38616fca836bb0ad053d4c4ed63423](https://github.com/Exeter-Computer-Science-Society/excs-website/commit/d6df8f1ffa38616fca836bb0ad053d4c4ed63423)
[#5fc2e1f175811db65ffa0a0f6fbf4f8285068541](https://github.com/Exeter-Computer-Science-Society/excs-website/commit/5fc2e1f175811db65ffa0a0f6fbf4f8285068541)
